language: ruby
rvm:
- 1.9.3
env:
  global:
    secure: mWU3Eii9Ffkf+LJNqovyOgYWzj2u9WVsdWjOcqxSeuTnb2PrYHivYg2W3ghMacFP7QyRXrmP3yk5q43IBG9SYYFPdl8ya7/9NtxQCrl1l0OGw4Z79Wfv1xEhNSyBmajFRq7M9nvjlhtk5se5OGMaKBUbNC92+klAQR4sSvbzpYw=
deploy:
  provider: rubygems
  gem: factor-connector-irc
  api_key:
    secure: mMY5ZBtkbojnbXBLCnMpvdokLoJU+RbeafrQ3CZpOGXK4+mg8hoY79kdNIYNImF4bhOh3G0Ol0ByCsBGcciX1hknWLyrv8ZNNxlhoDLgTozcTIi8Zyd1SkRD360LUxGn5cDOgX+7o226zh6p2B742dVcgIf8Y469cGxT855DpBg=
  on:
    tags: true
    all_branches: true
